/**
 * Official Indian Numbering System Currency Formatter
 * Examples: 150000 -> ₹1,50,000 | 500000 -> ₹5,00,000 | 1500000 -> ₹15,00,000
 */
export function formatINR(val) {
  if (val === null || val === undefined || isNaN(val)) return '₹0';
  const num = Math.round(Number(val));
  const str = num.toString();

  if (str.length <= 3) return '₹' + str;

  const lastThree = str.substring(str.length - 3);
  const otherDigits = str.substring(0, str.length - 3);
  const formattedOthers = otherDigits.replace(/\B(?=(\d{2})+(?!\d))/g, ',');

  return `₹${formattedOthers},${lastThree}`;
}

export const INDIAN_22_LANGUAGES = [
  'English',
  'Assamese (অসমীয়া)',
  'Bengali (বাংলা)',
  'Bodo (बर\')',
  'Dogri (डोगरी)',
  'Gujarati (ગુજરાતી)',
  'Hindi (हिंदी)',
  'Kannada (ಕನ್ನಡ)',
  'Kashmiri (कॉशुर)',
  'Konkani (कोंकणी)',
  'Maithili (मैथिली)',
  'Malayalam (മലയാളം)',
  'Manipuri (মৈতৈলোন্)',
  'Marathi (मराठी)',
  'Nepali (नेपाली)',
  'Odia (ଓଡ଼ିଆ)',
  'Punjabi (ਪੰਜਾਬੀ)',
  'Sanskrit (संस्कृतम्)',
  'Santali (ᱥᱟᱱᱛᱟᱲᱤ)',
  'Sindhi (सिंधी)',
  'Tamil (தமிழ்)',
  'Telugu (తెలుగు)',
  'Urdu (اردو)'
];

const baseEn = {
  subtitle_brand: "Independent Clinical & Policy Decision Navigation Engine",
  emergency: "EMERGENCY NOTICE: If you or a family member are experiencing a medical emergency, call 112 / 108 immediately or go directly to the nearest Casualty ER. Do not delay medical care for policy verification.",
  emergency_er: "Emergency ER: 112 / 108",
  site_lang: "App & Site Interface Language",
  tab1: "Upload & Extract",
  tab2: "Ask Your Policy",
  tab3: "Find Hospital Options",
  tab4: "Care Journey & Safety",
  telemetry: "Operational Telemetry",
  telemetry_sub: "Encrypted Ephemeral Session Scope",
  dpdp_header: "Privacy & DPDP Rules 2025",
  dpdp_consent: "I consent to temporary document processing for this session.",
  purge_btn: "Purge & Delete Session Data Now",
  privacy_accordion: "Privacy Policy & Retention Schedule",
  grievance_accordion: "Grievance Redressal & Support",
  admin_accordion: "Admin & CERT-In Console",
  disclaimer_footer: "Independent navigation system. Not medical advice or an insurance guarantee.",
  upload_header: "Upload Policy Document",
  upload_sub: "Upload your Base Health Insurance Policy (PDF)",
  upload_limit_note: "Limit 25MB per file • PDF (Max 50 pages)",
  load_demo_base: "Load Demo Base Policy",
  topup_expander: "Dual-Policy & Super Top-Up Comparison Engine",
  topup_desc: "Upload or load a secondary Super Top-Up policy to calculate combined sum insured and deductible triggers.",
  upload_topup_label: "Upload Secondary / Super Top-Up Policy (PDF)",
  load_demo_topup: "Load Demo Super Top-Up Policy",
  topup_deductible_label: "Top-Up Deductible Threshold (INR)",
  dual_breakdown: "Dual-Policy Protection Breakdown:",
  primary_cover: "Primary Policy Cover",
  topup_cover: "Top-Up Policy Cover",
  combined_si: "Combined Sum Insured",
  extracted_summary: "Extracted Policy Summary",
  base_coverage: "Base Policy Coverage",
  secondary_topup_coverage: "Secondary Super Top-Up Coverage",
  insurer_name: "Insurer Name",
  policy_name: "Policy Name",
  sum_insured: "Sum Insured",
  room_eligibility: "Room Eligibility",
  copay_terms: "Co-Pay Terms",
  preauth_req: "Pre-Auth Required",
  dl_pdf_summary: "Download Extracted Policy Summary (PDF)",
  dl_pdf_preauth: "Download Pre-Authorization TPA Form (PDF)",
  proc_lookup_header: "Procedure-Specific Sub-Limit & Document Lookup",
  cataract_sublimit: "Cataract Surgery Sub-Limit",
  cataract_val: "₹40,000 per eye",
  knee_waiting: "Joint Replacement Waiting Period",
  knee_val: "24 Months Specific Exclusion",
  daycare_eligibility: "Day Care Procedure Eligibility",
  daycare_val: "Covered (No 24h Mandatory Stay)",
  ask_header: "Ask Questions About Your Coverage",
  ask_input_placeholder: "Type your policy question (e.g., Is ICU room capped? What is pre-hospitalization limit?)...",
  send_btn: "Send",
  report_ticket: "Report Incorrect Guidance / Submit Feedback Ticket",
  submit_ticket_btn: "Submit Feedback Ticket",
  hosp_header: "Hospital Network & Room Matching",
  journey_header: "Care Journey, Claim Estimator & Safety Guidelines"
};

const devnagariIndicFallback = {
  ...baseEn,
  subtitle_brand: "स्वतंत्र नैदानिक और नीति निर्णय नेविगेशन इंजन",
  emergency: "आपातकालीन सूचना: यदि आपको या आपके परिवार को कोई चिकित्सा आपात स्थिति है, तो तुरंत 112 / 108 पर कॉल करें।",
  emergency_er: "आपातकालीन ER: 112 / 108",
  tab1: "अपलोड और निष्कर्ष",
  tab2: "अपनी पालिसी पूछो",
  tab3: "अस्पताल तम्भो",
  tab4: "सुरक्षा यात्रा",
  telemetry: "ऑपरेशनल टेलीमेट्री",
  telemetry_sub: "एन्क्रिप्टेड क्षणिक सत्र दायरा",
  dpdp_header: "गोपनीयता और DPDP नियम 2025",
  dpdp_consent: "मैं इस सत्र के लिए अस्थायी दस्तावेज़ प्रसंस्करण की सहमति देता हूँ।",
  purge_btn: "अभी सत्र डेटा मिटाएं और हटाएं",
  privacy_accordion: "गोपनीयता नीति और प्रतिधारण अनुसूची",
  grievance_accordion: "शिकायत निवारण और सहायता",
  admin_accordion: "व्यवस्थापक और CERT-In कंसोल",
  disclaimer_footer: "स्वतंत्र नेविगेशन प्रणाली। चिकित्सा सलाह या बीमा गारंटी नहीं।",
  upload_header: "नीति दस्तावेज़ अपलोड करें",
  upload_sub: "अपनी मूल स्वास्थ्य बीमा नीति (PDF) अपलोड करें",
  load_demo_base: "डेमो मूल नीति लोड करें",
  topup_expander: "दोहरी-नीति और सुपर टॉप-अप तुलना इंजन",
  topup_desc: "संयुक्त बीमा राशि और कटौती योग्य ट्रिगर की गणना के लिए एक द्वितीयक सुपर टॉप-अप नीति अपलोड करें।",
  load_demo_topup: "डेमो सुपर टॉप-अप नीति लोड करें",
  primary_cover: "प्राथमिक नीति कवर",
  topup_cover: "टॉप-अप नीति कवर",
  combined_si: "कुल संयुक्त बीमा राशि",
  extracted_summary: "निकाला गया नीति सारांश",
  base_coverage: "मूल नीति कवरेज",
  secondary_topup_coverage: "द्वितीयक सुपर टॉप-अप कवरेज",
  insurer_name: "बीमाकर्ता का नाम",
  policy_name: "नीति का नाम",
  sum_insured: "बीमा राशि",
  room_eligibility: "कमरे की पात्रता",
  copay_terms: "सह-भुगतान की शर्तें",
  preauth_req: "पूर्व-स्वीकृति आवश्यक",
  dl_pdf_summary: "नीति सारांश डाउनलोड करें (PDF)",
  dl_pdf_preauth: "पूर्व-स्वीकृति TPA फॉर्म डाउनलोड करें (PDF)",
  proc_lookup_header: "प्रक्रिया-विशिष्ट उप-सीमा और दस्तावेज़ खोज",
  cataract_sublimit: "मोतियाबिंद सर्जरी उप-सीमा",
  cataract_val: "₹40,000 प्रति आंख",
  knee_waiting: "घुटने के प्रतिस्थापन की प्रतीक्षा अवधि",
  knee_val: "24 महीने की विशिष्ट छूट",
  daycare_eligibility: "डे केयर प्रक्रिया की पात्रता",
  daycare_val: "कवर्ड (कोई 24 घंटे का अनिवार्य प्रवास नहीं)",
  ask_header: "अपनी कवरेज के बारे में प्रश्न पूछें",
  ask_input_placeholder: "अपनी नीति से संबंधित प्रश्न टाइप करें...",
  send_btn: "भेजें",
  report_ticket: "गलत मार्गदर्शन की रिपोर्ट करें / फीडबैक टिकट जमा करें",
  submit_ticket_btn: "फीडबैक टिकट जमा करें",
  hosp_header: "अस्पताल नेटवर्क और कमरा मिलान",
  journey_header: "देखभाल यात्रा, दावा अनुमानक और सुरक्षा दिशानिर्देश"
};

export const TRANSLATIONS = {
  English: baseEn,
  "Dogri (डोगरी)": devnagariIndicFallback,
  "Hindi (हिंदी)": devnagariIndicFallback,
  "Marathi (मराठी)": devnagariIndicFallback,
  "Nepali (नेपाली)": devnagariIndicFallback,
  "Sanskrit (संस्कृतम्)": devnagariIndicFallback,
  "Maithili (मैथिली)": devnagariIndicFallback,
  "Bodo (बर')": devnagariIndicFallback,
  "Konkani (कोंकणी)": devnagariIndicFallback,
  "Sindhi (सिंधी)": devnagariIndicFallback,
  "Bengali (বাংলা)": {
    ...baseEn,
    subtitle_brand: "স্বাধীন ক্লিনিকাল ও পলিসি সিদ্ধান্ত নেভিগেশন ইঞ্জিন",
    emergency: "জরুরি নোটিশ: অবিলম্বে ১১২ / ১০৮ নম্বরে কল করুন।",
    emergency_er: "জরুরি চিকিৎসা: ১১২ / ১০৮",
    tab1: "আপলোড ও সারাংশ",
    tab2: "পলিসি জিজ্ঞাসা করুন",
    tab3: "হাসপাতাল খুঁজুন",
    tab4: "নিরাপত্তা ও চিকিৎসা যাত্রা",
    proc_lookup_header: "প্রক্রিয়া-নির্দিষ্ট উপ-সীমা ও নথি অনুসন্ধান",
    cataract_sublimit: "ছানি অপারেশনের উপ-সীমা",
    cataract_val: "প্রতি চোখে ₹৪০,০০০",
    knee_waiting: "হাঁটু প্রতিস্থাপনের অপেক্ষার সময়কাল",
    knee_val: "২৪ মাস বিশেষ বাদ",
    daycare_eligibility: "ডে কেয়ার প্রক্রিয়ার যোগ্যতা",
    daycare_val: "কভার্ড (২৪ ঘণ্টার বাধ্যবাধকতা নেই)",
    ask_header: "আপনার কভারেজ সম্পর্কে প্রশ্ন জিজ্ঞাসা করুন",
    report_ticket: "ভুল তথ্যের রিপোর্ট করুন / প্রতিক্রিয়া টিকিট জমা দিন",
    submit_ticket_btn: "প্রতিক্রিয়া টিকিট জমা দিন"
  },
  "Gujarati (ગુજરાતી)": {
    ...baseEn,
    subtitle_brand: "સ્વતંત્ર ક્લિનિકલ અને પોલિસી નિર્ણય નેવિગેશન એન્જિન",
    emergency: "ઇમરજન્સી નોટિસ: તુરંત 112 / 108 પર કોલ કરો.",
    emergency_er: "ઇમરજન્સી ER: 112 / 108",
    tab1: "અપલોડ કરો",
    tab2: "પોલિસી પૂછો",
    tab3: "હોસ્પિટલ શોધો",
    tab4: "સુરક્ષા યાત્રા",
    proc_lookup_header: "પ્રક્રિયા-વિશિષ્ટ સબ-લિમિટ અને દસ્તાવેજ લુકઅપ",
    cataract_sublimit: "મોતિયાની સર્જરી સબ-લિમિટ",
    knee_waiting: "સાંધા બદલવાની પ્રતીક્ષા અવધિ",
    daycare_eligibility: "ડે કેર પ્રોસિજર યોગ્યતા",
    ask_header: "તમારા કવરેજ વિશે પ્રશ્નો પૂછો",
    report_ticket: "ફીડબેક ટિકિટ સબમિટ કરો"
  },
  "Tamil (தமிழ்)": {
    ...baseEn,
    subtitle_brand: "சுயாதீன மருத்துவ மற்றும் கொள்கை முடிவு வழிசெலுத்தல் இயந்திரம்",
    emergency: "அவசர அறிவிப்பு: உடனடியாக 112 / 108 ஐ அழைக்கவும்.",
    emergency_er: "அவசர சிகிச்சை: 112 / 108",
    tab1: "பதிவேற்றம்",
    tab2: "கொள்கை கேட்கவும்",
    tab3: "மருத்துவமனை தேடவும்",
    tab4: "பாதுகாப்பு பயணம்",
    proc_lookup_header: "செயல்முறை சார்ந்த துணை எல்லை மற்றும் ஆவண தேடல்",
    cataract_sublimit: "புரை அறுவை சிகிச்சை வரம்பு",
    knee_waiting: "மூட்டு மாற்று காத்திருப்பு காலம்",
    daycare_eligibility: "பகல்நேர சிகிச்சை தகுதி",
    ask_header: "உங்கள் கவரேஜ் பற்றி கேள்விகளைக் கேட்கவும்",
    report_ticket: "கருத்து சீட்டை சமர்ப்பிக்கவும்"
  },
  "Telugu (తెలుగు)": {
    ...baseEn,
    subtitle_brand: "స్వతంత్ర క్లినికల్ మరియు పాలసీ నిర్ణయ నావిగేషన్ ఇంజిన్",
    emergency: "అత్యవసర నోటీసు: వెంటనే 112 / 108 కి కాల్ చేయండి.",
    emergency_er: "అత్యవసర ER: 112 / 108",
    tab1: "అప్‌లోడ్ చేయండి",
    tab2: "పాలసీ ప్రశ్న అడగండి",
    tab3: "ఆసుపత్రులను కనుగొనండి",
    tab4: "రక్షణ ప్రయాణం",
    proc_lookup_header: "విధాన-నిర్దిష్ట ఉప-పరిమితి & పత్ర శోధన",
    cataract_sublimit: "కంటి శుక్లాల సర్జరీ ఉప పరిమితి",
    knee_waiting: "కీళ్ల మార్పిడి నిరీక్షణ కాలం",
    daycare_eligibility: "డే కేర్ విధానాల అర్హత",
    ask_header: "మీ కవరేజ్ గురించి ప్రశ్నలు అడగండి",
    report_ticket: "అభిప్రాయ రశీదును సమర్పించండి"
  }
};

export function getTranslation(lang, key) {
  const dict = TRANSLATIONS[lang] || baseEn;
  return dict[key] || baseEn[key] || key;
}
